"""made change

Revision ID: 3b459fa6227c
Revises: baa61f203a97
Create Date: 2026-03-29 14:13:27.651223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b459fa6227c'
down_revision = 'baa61f203a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_within_boundary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_within_boundary')

    # ### end Alembic commands ###
