"""added contact table

Revision ID: 5f07838f07d4
Revises: c4f3d7374293
Create Date: 2026-04-05 07:29:00.869290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f07838f07d4'
down_revision = 'c4f3d7374293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('email_primary', sa.String(length=150), nullable=True),
    sa.Column('email_secondary', sa.String(length=150), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=True),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region_state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_profiles')
    # ### end Alembic commands ###
