"""add remarks to attendance

Revision ID: 8005ac45184c
Revises: 1d5b7906d3c2
Create Date: 2026-03-30 02:10:09.854730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8005ac45184c'
down_revision = '1d5b7906d3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
