"""added plan for complaints

Revision ID: 88f2b9d6d5e3
Revises: dba2d1befca8
Create Date: 2026-04-06 21:07:17.375303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f2b9d6d5e3'
down_revision = 'dba2d1befca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaints_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('complaints_enabled')

    # ### end Alembic commands ###
