"""Added branding to schools

Revision ID: a9cdcb345766
Revises: 08314438e9f4
Create Date: 2026-03-27 04:12:24.736029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cdcb345766'
down_revision = '01d721351a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
