"""add geofencing and school notices

Revision ID: b130b93a06fd
Revises: a9cdcb345766
Create Date: 2026-03-29 10:05:44.349495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b130b93a06fd'
down_revision = 'a9cdcb345766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_within_boundary', sa.Boolean(), nullable=True))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('radius_meters', sa.Integer(), server_default='200', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('radius_meters')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('is_within_boundary')

    op.drop_table('school_notices')
    # ### end Alembic commands ###
