"""Added biometric WebAuthn columns to User

Revision ID: c4f3d7374293
Revises: 083a04b982b1
Create Date: 2026-04-04 10:33:19.561330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f3d7374293'
down_revision = '083a04b982b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_id')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
