"""add participant_type and gps to attendance

Revision ID: d0b355ced907
Revises: b130b93a06fd
Create Date: 2026-03-29 11:46:01.885661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b355ced907'
down_revision = 'b130b93a06fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('participant_type', sa.String(length=20), server_default='student', nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('participant_type')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('atitude')

    # ### end Alembic commands ###
