"""add passkey table

Revision ID: d8e562c7c921
Revises: 5f07838f07d4
Create Date: 2026-04-06 07:34:07.310014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e562c7c921'
down_revision = '5f07838f07d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_passkeys_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_passkeys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_passkeys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_passkeys_credential_id'))

    op.drop_table('user_passkeys')
    # ### end Alembic commands ###
