"""add communications

Revision ID: dba2d1befca8
Revises: d8e562c7c921
Create Date: 2026-04-06 17:46:16.416487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba2d1befca8'
down_revision = 'd8e562c7c921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_type', sa.String(length=30), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_threads_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_threads_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_threads_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_threads_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_threads_thread_type'), ['thread_type'], unique=False)

    op.create_table('complaint_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_to_id'], ['complaint_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['complaint_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('complaint_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_thread', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['complaint_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_complaint_thread_user')
    )
    with op.batch_alter_table('complaint_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_participants_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_participants_user_id'), ['user_id'], unique=False)

    op.create_table('complaint_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('media_kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['complaint_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_attachments_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_attachments_message_id'))

    op.drop_table('complaint_attachments')
    with op.batch_alter_table('complaint_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_participants_thread_id'))

    op.drop_table('complaint_participants')
    with op.batch_alter_table('complaint_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_messages_created_at'))

    op.drop_table('complaint_messages')
    with op.batch_alter_table('complaint_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_threads_thread_type'))
        batch_op.drop_index(batch_op.f('ix_complaint_threads_student_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_threads_school_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_threads_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_threads_created_by_user_id'))

    op.drop_table('complaint_threads')
    # ### end Alembic commands ###
